### ISSUE TITLE
The dataset can not be downloaded. If there is a question?

### ISSUE THREAD

**Issue by sunhongze** [CompVis/vunet#10]

**Comment by gsygsy96** [comment]
Have you find solution?

**Comment by sunhongze** [comment]
已经更新了 可以下载了

**Comment by raven38** [comment]
I can't access http://129.206.117.181:8080/.

**Comment by pei0113** [comment]
@sunhongze 請問你那邊有下載成功的training data能分享嗎??

**Comment by donghaoye** [comment]
@sunhongze 请问可以分享一下下载的数据吗？

**Comment by heerduo** [comment]
@sunhongze麻烦给下数据集的连接吧？打不开

**Comment by ChenCherry** [comment]
遇到同样问题，不知道各位解决了没有？请求帮助

**Comment by pesser** [comment]
Sorry about that, there was a problem with the server. [Data](http://129.206.117.181:8080/)'s online again!
