### ISSUE TITLE
Some questions about the code BN&activation

### ISSUE THREAD

**Issue by OwalnutO** [CompVis/vunet#12]
Thanks for your brilliant code!

However, when I try to modify your code, it takes me a lot of time to read and understand your code. 

Do you only use "elu" in your code and only in resnet block? I don't find any use of activation in the network definition in model.py. 

The same issue is with BN. I don't find it in the network definition which makes me confused when I want to add new network module.

Thanks!

**Comment by pesser** [comment]
The network architectures can be found in [models.py](../blob/master/models.py) and the building blocks in [nn.py](../blob/master/nn.py). Yes, only ELU activations are used and they are only used within residual blocks (defined in [nn.py](../blob/master/nn.py)).
I'm not sure about BN - do you mean batch normalization? Our code does not use batch normalization.

Best
Patrick
