### ISSUE TITLE
Some question about two round

### ISSUE THREAD

**Issue by heerduo** [CompVis/vunet#14]
Hello,
 I am getting the following error when I run the coed:
python main.py --config <dataset>_retrain.yaml --retrain --checkpoint <path to checkpoint of first round>

DataLossError (see above for traceback): Unable to open table file ./log/2018-10-11T10:11:14/checkpoints: Failed precondition: ./log/2018-10-11T10:11:14/checkpoints: perhaps your file is in a different file format and you need to use a different restore operator?

**Comment by pesser** [comment]
Hi,

The checkpoint flag expects a path to a tensorflow checkpoint, it should look similiar to this

    python main.py --config deepfashion_retrain.yaml --retrain --checkpoint ./log/2018-10-11T10:11:14/checkpoints/model.ckpt-100000

adapted to the dataset you train on and the exact path to the previously saved checkpoint.

Best
Patrick

**Comment by heerduo** [comment]
Wow, the program has run successfully. Thanks a lot.
