### ISSUE TITLE
I had trouble using this in window

### ISSUE THREAD

**Issue by richard0326** [CompVis/vunet#16]
had error with 'os.mkdir' function
[Error 123] The filename, directory name, or volume label syntax is incorrect: <fileName>

I tracked the error and changed
'%Y-%m-%dT%H:%M:%S.' to '%Y-%m-%dT%H-%M-%S.'

Window can't allow colons in file names.

**Comment by pesser** [comment]
Thanks for pointing it out! Feel free to send a PR, might be helpful for others.

**Comment by pesser** [comment]
Fixed in 022049934194169770ced3660f739c1879d23441
