### ISSUE TITLE
I have question for batch size

### ISSUE THREAD

**Issue by richard0326** [CompVis/vunet#19]
what is the difference between 'batch_size' and 'init_batches'

**Comment by pesser** [comment]
We use data dependent initialization, i.e. a forward pass with an initialization batch is performed and the weights are rescaled such that we have activations of the layers approximately distributed according to a standard normal distribution. When you have to train with relatively small batch sizes it might make sense to increase the batch size for the initialization pass to get better statistics - that's what `init_batches` is for.
Best
Patrick

**Comment by richard0326** [comment]
Thanks Patrick
Can you help me understand the difference between 'test_sample' and 'sample' in the output??

**Comment by pesser** [comment]
`sample` produces an image with an appearance representation inferred from an appearance input image via the learned posterior and `test_sample` produces an image an appearance representation sampled from the learned appearance prior, i.e. it does not need an appearance input and simply produces a random appearance.
