### ISSUE TITLE
Error on market Data

### ISSUE THREAD

**Issue by mahfujau** [CompVis/vunet#2]
Hi,

I am getting the following error when I run the code:
$python main.py --config market.yaml

Traceback (most recent call last):
  File "main.py", line 449, in <module>
    out_dir, logger = init_logging(opt.log_dir)
  File "main.py", line 21, in init_logging
    os.makedirs(out_base_dir, exist_ok = True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

**Comment by pesser** [comment]
Hi,
you are probably trying to run the code with a Python 2.x version as the `exist_ok` keyword was only introduced in Python 3. The code only supports Python 3 so switching to it should work.
Best
Patrick

**Comment by mahfujau** [comment]
Thank you so much.

**Comment by donghaoye** [comment]
@mahfujau Could you send me the datasets?
