### ISSUE TITLE
Undefined name 'out_dir' in batches.py

### ISSUE THREAD

**Issue by cclauss** [CompVis/vunet#21]
_Undefined names_ have the potential to raise _NameError_ at runtime.

[flake8](http://flake8.pycqa.org) testing of https://github.com/CompVis/vunet on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./batches.py:57:26: F821 undefined name 'out_dir'
    fname = os.path.join(out_dir, name + ".png")
                         ^
1     F821 undefined name 'out_dir'
1
```

**Comment by pesser** [comment]
thanks, that was dead code!
