### ISSUE TITLE
I want to try retraining can you help me?

### ISSUE THREAD

**Issue by richard0326** [CompVis/vunet#23]
I tried your tf ver over 13 and it worked great!!
So now I want to try retraining. But I'm not sure how...?

`python main.py --config <dataset>_retrain.yaml --retrain --checkpoint <path to checkpoint of first round>`

I tried this code in my cmd like this:
`python main.py --config market_retrain.yaml --retrain --checkpoint model.ckpt-100000.data-00000-of-00001`

and
`python main.py --config market_retrain.yaml --retrain --checkpoint model.ckpt-100000.index`

and
`python main.py --config market_retrain.yaml --retrain --checkpoint model.ckpt-100000.meta`

But still it doesn't work...
By the way, I have copied the model's checkpoint file to same directory to 'main.py'.

How can I retrain??

**Comment by pesser** [comment]
The checkpoint path should read `model.ckpt-100000` without any ending.

Thanks for letting me know that it works for you!

**Comment by richard0326** [comment]
Thank you so much!!

**Comment by HrsPythonix** [comment]
cannot restore , tensorflow v1.11.0, errors are below:

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key enc_up/conv2d_14/V not found in checkpoint
	 [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[{{node save/RestoreV2/_493}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_306_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by HrsPythonix** [comment]
Also when I change my version to 1.5.0, still error:

tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [32] rhs shape= [128]
	 [[Node: save/Assign_1024 = Assign[T=DT_FLOAT, _class=["loc:@enc_up/dense_0/g"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](enc_up/dense_0/g/Adam_1, save/RestoreV2_1024/_1529)]]
......
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [32] rhs shape= [128]
	 [[Node: save/Assign_1024 = Assign[T=DT_FLOAT, _class=["loc:@enc_up/dense_0/g"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](enc_up/dense_0/g/Adam_1, save/RestoreV2_1024/_1529)]]

**Comment by HrsPythonix** [comment]
By the way, I changed the batch_size to 1 and box_factor to 0 in order to do testing

**Comment by HrsPythonix** [comment]
fix, I should change the box_factor to 2 as well as the training does.
