### ISSUE TITLE
How to directly use your pretrained model to test?

### ISSUE THREAD

**Issue by HrsPythonix** [CompVis/vunet#24]
I see in main.py, there are four modes including "train", "test", "add_reconstructions", "transfer". But only train is implemented, what should I do if I want to directly use your pretrained model to test on Open Dataset or other images? Any instruction?

Thanks.

**Comment by pesser** [comment]
The methods for testing are already available on the Model object (i.e. `test`, `reconstruct`, `transfer`), you just have to call them. For example, to generate images with randomly sampled appearances try this (after if `opt.mode == "train"` in the main):

```
    elif opt.mode == "test":
        if not opt.checkpoint:
            raise Exception("Testing requires --checkpoint")
        batch_size = opt.batch_size
        img_shape = 2*[opt.spatial_size] + [3]
        data_shape = [batch_size] + img_shape
        valid_batches = get_batches(data_shape, opt.data_index, train = False)
        model = Model(opt, out_dir, logger)
        model.restore_graph(opt.checkpoint)

        for i in trange(valid_batches.n // batch_size):
            X_batch, C_batch = next(valid_batches)
            x_gen = model.test(C_batch)
            for k in x_gen:
                plot_batch(x_gen[k], os.path.join(
                    out_dir,
                    "testing_{}_{:07}.png".format(k, i)))
```

For custom datasets, you'll first have to convert your dataset to a pickle file as described in the section `Other Datasets` of the readme.

**Comment by HrsPythonix** [comment]
Thank you for your kindly reply.

**Comment by HrsPythonix** [comment]
@pesser How do you deal with the box_factor while testing?

**Comment by HrsPythonix** [comment]
model = Model(opt, out_dir, logger) and you use opt instead of config here, what argument do you add in the argparse? And what value?

**Comment by longintlong** [comment]
> The methods for testing are already available on the Model object (i.e. `test`, `reconstruct`, `transfer`), you just have to call them. For example, to generate images with randomly sampled appearances try this (after if `opt.mode == "train"` in the main):
> 
> ```
>     elif opt.mode == "test":
>         if not opt.checkpoint:
>             raise Exception("Testing requires --checkpoint")
>         batch_size = opt.batch_size
>         img_shape = 2*[opt.spatial_size] + [3]
>         data_shape = [batch_size] + img_shape
>         valid_batches = get_batches(data_shape, opt.data_index, train = False)
>         model = Model(opt, out_dir, logger)
>         model.restore_graph(opt.checkpoint)
> 
>         for i in trange(valid_batches.n // batch_size):
>             X_batch, C_batch = next(valid_batches)
>             x_gen = model.test(C_batch)
>             for k in x_gen:
>                 plot_batch(x_gen[k], os.path.join(
>                     out_dir,
>                     "testing_{}_{:07}.png".format(k, i)))
> ```
> 
> For custom datasets, you'll first have to convert your dataset to a pickle file as described in the section `Other Datasets` of the readme.

Hi!  My question is  that what does the three files(model-ckpt.index   mode-ckpt.meta  model.ckpt-100000.data-00000-of-00001)  of the market's pretrained model file means?
Thanks!

**Comment by longintlong** [comment]
> The methods for testing are already available on the Model object (i.e. `test`, `reconstruct`, `transfer`), you just have to call them. For example, to generate images with randomly sampled appearances try this (after if `opt.mode == "train"` in the main):
> 
> ```
>     elif opt.mode == "test":
>         if not opt.checkpoint:
>             raise Exception("Testing requires --checkpoint")
>         batch_size = opt.batch_size
>         img_shape = 2*[opt.spatial_size] + [3]
>         data_shape = [batch_size] + img_shape
>         valid_batches = get_batches(data_shape, opt.data_index, train = False)
>         model = Model(opt, out_dir, logger)
>         model.restore_graph(opt.checkpoint)
> 
>         for i in trange(valid_batches.n // batch_size):
>             X_batch, C_batch = next(valid_batches)
>             x_gen = model.test(C_batch)
>             for k in x_gen:
>                 plot_batch(x_gen[k], os.path.join(
>                     out_dir,
>                     "testing_{}_{:07}.png".format(k, i)))
> ```
> 
> For custom datasets, you'll first have to convert your dataset to a pickle file as described in the section `Other Datasets` of the readme.

Hi! How can i convert my data to the pickle file? Do you have convert code?
