### ISSUE TITLE
About In-plane normalization

### ISSUE THREAD

**Issue by liruilong940607** [CompVis/vunet#25]
I have a question about your 'In-plane normalization' for the pose task.

Have you try the performance of your pose task without the 'In-plane normalization'? With a little modification of your code ( 'self.xn' -> 'self.x' and 'self.cn' -> 'self.c'), it seems easy to accomplish. 

I'm doing this experiment. Although the model hasn't converge, the performance seems bad. So I want to ask you about this since no ablation experiments on 'In-plane normalization' is done in your paper.

Looking forward to your reply.

**Comment by pesser** [comment]
Yes we did that, too. You can find an example of this ablation on the [poster](https://compvis.github.io/vunet/images/vunet_poster.pdf)

The performance should be okay but you might have to increase the weight of the KL regularization. It mostly fails for large changes in viewpoints, such as half body -> full body as in the example on the poster. Furthermore, this is the exact setup used for the shoes and handbags examples.

Best
Patrick
