### ISSUE TITLE
Transfer result not good

### ISSUE THREAD

**Issue by HrsPythonix** [CompVis/vunet#26]
I write addition code to do transfer, as below:

```
    parser.add_argument("--src_img", required = True, help = "path to src_img")
    parser.add_argument("--tar_img", required = True, help = "path to tar_img")
    parser.add_argument("--src_jo", required = True, help = "path to src_jo")
    parser.add_argument("--tar_jo", required = True, help = "path to tar_jo")
```

```
elif opt.mode == "transfer":
        if not opt.checkpoint:
            raise Exception("transfer requires --checkpoint")
        config['batch_size'] = 1
        model = Model(config, out_dir, logger)
        model.restore_graph(opt.checkpoint)
        x_encode, c_encode, c_decode = model.prepare_tranfer(opt.src_img, opt.src_jo, opt.tar_img, opt.tar_jo)
        x_gen = model.transfer(x_encode, c_encode, c_decode)
        plot_batch(x_gen, os.path.join(out_dir, "testing.png"))
```

```
    def prepare_tranfer(self, src_img_path, src_joints_path, tar_img_path, tar_joints_path):
        from batches import load_img, make_joint_img, preprocess, normalize
        joint_order = ['cnose', 'cneck', 'rshoulder', 'relbow', 'rwrist', 
                       'lshoulder', 'lelbow', 'lwrist', 'rhip', 
                       'rknee', 'rankle', 'lhip', 'lknee', 'lankle', 
                       'reye', 'leye', 'rear', 'lear']
        imgs = [load_img(src_img_path, target_size = self.img_shape), load_img(tar_img_path, target_size = self.img_shape)]
        imgs = np.stack(imgs)
        imgs = preprocess(imgs)

        joints_coordinates = [np.load(src_joints_path), np.load(tar_joints_path)]
        joints = []
        for joints_c in joints_coordinates:
            joints.append(make_joint_img(self.img_shape, joint_order, joints_c))
        joints = np.stack(joints)
        joints = preprocess(joints)

        nimgs, njoints = normalize(imgs, joints_coordinates, joints, joint_order, 2)
        x_encode = np.stack([nimgs[0]])
        c_encode = np.stack([njoints[0]])
        c_decode = np.stack([joints[1]])
        return x_encode, c_encode, c_decode
```
The prepare_tranfer function is written following the ` __next__()` in batches.py. joints_coordinate are extracted from index.p file.

the src_img:
![img_a](https://user-images.githubusercontent.com/16586180/48184608-81989100-e36d-11e8-8616-384341d8d4c1.jpg)

the tar_img:
![img_b](https://user-images.githubusercontent.com/16586180/48184579-72b1de80-e36d-11e8-8ad0-fd629cec1971.jpg)

result:
![testing](https://user-images.githubusercontent.com/16586180/48184648-9f65f600-e36d-11e8-88ba-9d6f9fa7ca1a.png)

You can see clearly that this is not a good result, is there some mistake in the code?

**Comment by HrsPythonix** [comment]
Problem fixed, I forgot to scale the coordinates to image size.

**Comment by dc3ea9f** [comment]
> Problem fixed, I forgot to scale the coordinates to image size.

Hi,

I am trying to run the code with `transfer` mode on the basis of your codes. Can you provide the code of this?

Thank you so much!

**Comment by HrsPythonix** [comment]
> > Problem fixed, I forgot to scale the coordinates to image size.
> 
> Hi,
> 
> I am trying to run the code with `transfer` mode on the basis of your codes. Can you provide the code of this?
> 
> Thank you so much!


I have added the transfer code in main.py, you can see my fork repo here, in "transfer" branch:
https://github.com/HrsPythonix/vunet/tree/transfer

An example has been put in "sample" dir.

Here is a sample cmd:
```
python main.py --config deepfashion_retrain.yaml --mode transfer --checkpoint ./deepfashion1/model.ckpt-100000 --src_img ./sample/img_a.jpg --src_jo ./sample/jo_a.npy --tar_jo ./sample/jo_b.npy --tar_img ./sample/img_b.jpg 
```
The joint coordinate is a 18*2 array, just like the format in dataset.
And in fact, tar_img is not necessary in the model, so you may pass a random image path.

**Comment by dc3ea9f** [comment]
Thanks a lot!

**Comment by dc3ea9f** [comment]
When using market dataset for transfer, I face the similar problem like [this](https://github.com/CompVis/vunet/issues/23#issuecomment-436894319):

```
Assign requires shapes of both tensors to match. lhs shape= [24,128] rhs shape= [24,64]
         [[Node: save/Assign_963 = Assign[T=DT_FLOAT, _class=["loc:@enc_up/dense_0/V"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](enc_up/dense_0/V/Adam, save/RestoreV2/_2119)]]
         [[Node: save/RestoreV2/_2126 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1940_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:967)]]
```

I am using tensorflow `1.10.1`, and following your comments in [this](https://github.com/CompVis/vunet/issues/23), I change the `box_factor` to 2, and `batch_size` to 1 in `market_retrain.yaml`, but it still occur errors when restore.

Can you help me?

Thanks!

**Comment by HrsPythonix** [comment]
You can refer to the market_retrain.yaml, the box_factor in it is 1, so you should change the box_factor to 1.  Remember to change --config.

You can also paste your cmd.

**Comment by dc3ea9f** [comment]
Oh, I forget to modify the `box_factor` value in [`main.py-L510`](https://github.com/HrsPythonix/vunet/blob/3768e18cfed6bdb4a8303cda031739cc327cda5e/main.py#L510) and [`main.py-L452`](https://github.com/HrsPythonix/vunet/blob/3768e18cfed6bdb4a8303cda031739cc327cda5e/main.py#L452). 

After modified these, the program can restore graph and do transfer smoothly.

I suggest you modifying the `box_factor` value in these two codes to the value that related to the dataset.

Thanks.
