### ISSUE TITLE
Pretrained models and test code

### ISSUE THREAD

**Issue by mzemlyanikin** [CompVis/vunet#3]
Hi!
Thanks for nice network, your results look very promising!
I have two questions:
Are going to share pretrained models?
And I looked at code and haven't found implementation for test stage, do you have any plans to do it? 
Thanks a lot.

**Comment by pesser** [comment]
Hi,
Currently we do not plan on adding additional code for testing but if you need anything specific, feel free to write me an email! Pretrained models will be uploaded during CVPR.
Best
Patrick
