### ISSUE TITLE
nin and other nn functions

### ISSUE THREAD

**Issue by darylfung96** [CompVis/vunet#30]
Hi there,

thank you very much for sharing your open source code. This has been very helpful for understanding how variational Unet works. I have a question though. Why do you implement nin, dense, etc as your own function instead of using tensorflow built-in ones? Would there be performance or accuracy issues if we are using the tensorflow ones?

**Comment by pesser** [comment]
Hi,
This is mostly done to implement weight normalization and because we tried a lot of different variants during development. But there should be no fundamental reason to not get it working with similar implementations of these layers.
