### ISSUE TITLE
How background is handled on COCO

### ISSUE THREAD

**Issue by ndrplz** [CompVis/vunet#32]
Hi @pesser ,

congrats for this impressive work and thank you for sharing the code with the community.

I was wondering how the backgroud is handled when using the COCO dataset. When you show the results, for example [here](http://129.206.117.181:8080/runs/coco_transfer.png) or in figure 1 of the paper, do you segment the people after the generation? 

As far as I can tell from the paper, when the background is present in the source image, e.g. in Market1501, also the samples show some noisy background. The smooth gray background for the COCO samples is confusing me.

Thank you,
A

**Comment by pesser** [comment]
For COCO we simply used the provided segmentation masks to make the background gray in a preprocessing step. No need to segment again after generation because the network directly learns to produce gray backgrounds.
Best
Patrick
