### ISSUE TITLE
Error in batches.py

### ISSUE THREAD

**Issue by Rong-Zhi** [CompVis/vunet#33]
Hi, many thanks for sharing this excellent project code. But I think batches.py line 280 and line 281 should follow the format:

_cv2.warpPerspective(img, M, (width,height), borderMode = cv2.BORDER_REPLICATE)_

Please correct me if I'm wrong.

**Comment by LiUzHiAn** [comment]
@Rong-Zhi  Hi,

After generating a stickman image from the keyponits coordinates, what is the purpose of normalizing the original image and stickman image? I have no idea about what the code normalizes exactly. Thanks.
